### PR TITLE
Fix images_rc.py for pyqt5/py3

### PR DESCRIPTION
**Pull request by dougrizeakos**

### CODE REVIEW

**Review by mds-dwa — APPROVED** [review]
Seems fine to me.

**Comment by gj-dwa** [comment]
I wonder this should be merged into python3 branch

**Comment by mdsandell** [comment]
It sounds like the b"string" is equivalent to "string" in python2, so it won't hurt anything, but it doesn't help either. If this file is already different in the python3 branch (I think it is but am not at a place to check), then I agree with Gyedo that changes should only be there. If the file's the same, let's do the change here.

**Comment by dougrizeakos** [comment]
Ah I didn't see the python3 branch. Looks like the change is already there, thanks!

**Pull request closed without merging**
