### PR TITLE
Make the icon installation optional

### PR DESCRIPTION
**Pull request by sebastianelsner**
Hej,

we do not want to install the icons, so I made the icon installation optional. Would this be a change you accept? If yes, I would add docs etc.

one would install with:

pip install usdmanager[icons]

Many thanks!

Sebastian

### CODE REVIEW

**Review by mdsandell — APPROVED** [review]

**Comment by mdsandell** [comment]
I think this is a perfect idea, so if you want to include the docs changes with the pull, that is probably for the best. @gj-dwa may need you to sign the CLA for this project if you and/or your company haven't done so already.

**Comment by sebastianelsner** [comment]
Thanks! Will do. do you think it makes sense to update the python 2 branch as well?

**Comment by mdsandell** [comment]
Yeah, when I was managing the project more full-time, I tried to keep the main python 2 code as the canonical source, and the python3 branch just with the handful of overrides that made it different. I’m not sure if DreamWorks has changed their philosophy on that, but Gyedo could likely speak to it. I am happy to see more and more places moving to python3 though!

**Comment by sebastianelsner** [comment]
Ok so I will probably make two prs

**Comment by sebastianelsner** [comment]
So, it seems setuptools only is not able to handle extra installs on the command line. Therefore the docs would need to change a bit more extensively.

Install the base package:

python setup.py install

Install the extras using pip:

pip install usdmanager[icons]

Would that be acceptable or does that break too much in existing build pipelines around studios? 

I can also keep this separate in our own repo. No harm done. :)

**Comment by gj-dwa** [comment]
Thank you @sebastianelsner for your contribution. Could you sign the [contributor agreement](http://www.usdmanager.org/USDManagerContributorLicenseAgreement.pdf) and email that to [usdmanager@dreamworks.com](mailto:usdmanager@dreamworks.com)?

**Comment by sebastianelsner** [comment]
After more discussion, I decided to close the pull request, because the changes would be too extensive for the benefit it has to others.
Thank you for your collaboration thus far :)

**Pull request closed without merging**
